### ISSUE TITLE
Custom test failure messages?

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#12]
Sometimes some test assertions require custom failure messages. Is it supported by the test framework? There are of course always the clunky myjinxin way:

1. Set one variable to string A if condition passes, else set it to string B
2. Write a test assertion that compares said variable should equal string A
3. If test fail, the message would say something along `Expected "condition fulfilled", got "did not fulfill condition"`

But something cleaner and easier to you would be better.

**Comment by nomennescio** [comment]
Yes it is supported. See for an example [the test code of the framework](https://github.com/Codewars/ttester-codewars/blob/master/test/test-custom.4thl)
