### ISSUE TITLE
Dynamic number of elements on the stack during testing?

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#13]
If I want to test a function that pop/push variable number of items on the stack depending on input (think of registers, different opcodes consume/produce different number of items from the stack and touches different amount of registers), is there a good way to generate random tests for it without resorting to complicated workarounds like custom validation function while relying on #12? Test assertion code seems to be static so I cannot issue dynamic/conditional test assertions at runtime. Or can I use something else to generate the test code?

**Comment by nomennescio** [comment]
Everything is dynamic in Forth, also the test code. It's only limited by your imagination. 
Look for example at the test code I wrote for a yet-to-be-approved Forth translation of ['parseInt() reloaded'](https://www.codewars.com/kata/parseint-reloaded/forks/forth):

`: times { xt n -- } n 0 +do xt execute loop ;`
`  : shouldbe { s len } <{ s len parseint -> s len predefined-solution }> ;`
`  :noname ten$ -$+ one$+ shouldbe ; 100 times`
`  :noname one$ 100$+ and$+ ten$+ -$+ one$+ shouldbe ; 100 times`

The `shouldbe` is evaluated at runtime, but could just as easily have a dynamic stack input.
