### ISSUE TITLE
`discode` does not work on runner

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#14]
Some commands like `see` and `discode` does not work properly on the runner. `see` works fine for colon-defined functions but fails for built-in operators (after printing something like `Code +`):

```
in file included from *OS command line*:-1
tests.4th:4: No such file or directory
see >>>+<<<
Backtrace:
$7F4CA0458C40 throw 
$0 
$7F4CA0472298 slurp-fid 
$7F4CA0472558 gdb-addr-sep-char 
$A 
$7F4CA046D6A8 discode 
$7F4CA046E060 seecode 
$7F4CA046E5F0 xt-see 
$55C57843C1C8 
$7F4CA046E848 name-see
```

Which is related to how `discode` would fail:

```
in file included from *OS command line*:-1
tests.4th:4: No such file or directory
' + 8 >>>discode<<<
Backtrace:
$7F0FBE510C40 throw 
$0 
$7F0FBE52A298 slurp-fid 
$7F0FBE52A558 gdb-addr-sep-char 
$A
```

(I think there are a few more commands that don't work but I forgot which)

It's not `Undefined word`, so GForth recognizes `discode`, but failed due to some other reasons.

But [according to official documentation](https://www.complang.tuwien.ac.at/forth/gforth/Docs-html/Common-Disassembler.html) at least, shouldn't `discode` fall back to `dump` if no disassembler is available? `dump` works fine on the runner though. Did something *pretend* there are disassemblers and only fail when actually trying to call them (due to something like file permission)?

**Comment by kazk** [comment]
See https://stackoverflow.com/questions/44014281/dissassembly-of-forth-code-words-with-see and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=655550

Looks like a workaround is to set [`ptrace_scope`](https://www.kernel.org/doc/Documentation/security/Yama.txt) to `0` (or run as `root`), but I'm not doing that for security reasons.

Maybe newer versions of gforth doesn't have this issue, but `0.7.3` is the latest stable and I don't really want to use unstable releases that requires us to build from source.

**Comment by nomennescio** [comment]
There's actually a preview `0.7.9` in the make *since 2020*, so don't hold your breath. I'm closing this issue for now. When a new version becomes available we will request a new version of gforth on CW.
