### ISSUE TITLE
Forth: "WRONG NUMBER OF FP RESULTS: run-tests"

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/ttester-codewars#5]
If user code produces more than required values on the FP stack, `WRONG NUMBER OF FP RESULTS: run-tests` is displayed.

1. This message is displayed *after* "Test passed/failed" message.

![image](https://user-images.githubusercontent.com/14909989/62668941-4bea0c80-b9c0-11e9-9c0b-b55ae35bd46e.png)

2. Shouldn't this cause test to fail? If the normal stack has incorrect number of integers the test will fail with `Wrong number of results, expected 1 , got x` after all, so FP stack probably should have the same behaviour.

**Comment by nomennescio** [comment]
The FP stack is not yet nicely integrated into this test framework, and remains to be done.

**Comment by nomennescio** [comment]
The test framework currently only tests the data stack, and hence only integer values. You can use the F{ and F} words from the original framework to explicitly test for floating point values.

**Comment by nomennescio** [comment]
Small fix with 2b5cc6cb691e2acbbdf02f88ed6e0cf1263dd888. Still full floating point support needs to be added.

**Comment by nomennescio** [comment]
Full floating point support added with 5afafb78cda95c0ff87251819d65b9d01817fdc1 . Currently only comparisons with `f<>` are supported.

**Comment by nomennescio** [comment]
Hi @kazk, I noticed Github has moved from CircleCI to Github Actions, can you check what needs to be done to migrate?

**Comment by nomennescio** [comment]
Migrated using default `ubuntu-latest`.
