### ISSUE TITLE
Dropping past the arguments stack causes test display to show wrong numbers

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#6]
Let's say I have the simplest function ever:
```forth
: cat ;

s" example" describe#{
  s" returns what is passed in" it#{
    <{ 1 cat -> 1 }>
  }#
}#
```

The integer stack actually has 4 values below the input argument:

![image](https://user-images.githubusercontent.com/14909989/62670868-43490480-b9c7-11e9-9bb5-74aafd186325.png)

Dropping past them will cause problems. Besides #1, it also causes the display to become something like `Wrong number of results, expected -3 , got -4`.

**Comment by nomennescio** [comment]
Showing the wrong number of results in case of stack underflow is a "feature" of the original test framework. I'll see if I can gently fix that without causing too much problems.

**Comment by kazk** [comment]
I'll close this when #9 is deployed.

**Comment by kazk** [comment]
Deployed
