### ISSUE TITLE
Prevent users from manipulating return stack past user's frame

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#7]
As it currently stands a trivial `r>`  can bypass any `it` block, which is probably too trivial to do. Doing it more sometimes terminates the tests immediately depending on the number of `r>`s.

**Comment by nomennescio** [comment]
This is a core feature of Forth, its flexible control structures that can be redefined by the user entirely depend on being able to manipulate the return stack. Yes, it is possible to crash a test by doing this. It is not possible to accidently pass a test however. In case a specific Kata author or translator wants to disable stack manipulations, he can always disable it in 'preloaded.4th'. In general, it might actually be required to have a Kata manipulate the return strack. It's therefore not a good idea to block it all together by the framework.

For an example how to disable Forth words, look at the test cases in [Sum of Two Integers](https://www.codewars.com/kata/5a9c35e9ba1bb5c54a0001ac)

`: + 2drop rnd ; : - 2drop rnd ;`

**Comment by nomennescio** [comment]
Theoretically, it might be possible to redefine ALL stack manipulating words to include stack over- and underflow checking. That would be however far out of scope of this simple test framework.
