### ISSUE TITLE
Data stack is not empty in user code

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/ttester-codewars#8]
Okay, this is related to #6 but is (probably) a separate issue of itself because it means `depth` will return the wrong result and doing varargs operations will require the size appended at the end, which is not desirable for various reasons.

e.g:

```
: sum 0 begin depth 1 > while + repeat ;

s" example" describe#{
  s" returns sum" it#{
    <{ sum -> 0 }>
    <{ 5 sum -> 5 }>
    <{ 4 5 sum -> 9 }>
    <{ 1 2 3 4 5 sum -> 15 }>
  }#
}#
```

On the runner `depth 1 >` needs to be changed to `depth 5 >` because the original stack already has some values on them.

Shouldn't those initial 4 values (presumably test time information) be stored on the return stack (temporarily) instead? Or at least be isolated to the user so they aren't in the open and become a nuisance to user code's operations.

**Comment by nomennescio** [comment]
In Forth typically upon entering ANY word, using the 'depth' parameter is worthless. The whole concept of stack languages is that you constantly have data on the stack 'below' your own stack parameters. Forth typically NEVER checks the number of parameters.

**Comment by Voileexperiments** [comment]
Yes, but why are the timing data exposed to the users in the data stack right below the actual input? I think they can be put on the return stack below user function's return address and then user code doesn't have to be concerned about these 4 numbers that they don't care about (not to mention the timing info is very fragile atm because of this). After all, loop indices are stored on the return stack too. And if they can pop from the return stack they can practically do anything anyways, so putting the timing data there isn't really an issue.

**Comment by nomennescio** [comment]
I understand your remark, but in general _anything_ can be on the datastack, and Forth programmers _really_ should not touch those anyway (unless intended of course). Moving it to the return stack should not make much of a difference.

I you want variable number of arguments (which can sometimes be useful), use a count as the first argument, as is customary in many languages. Else, use custom datastructures, or parse a string, or use a guard value.  But don't use 'depth' as an absolute value.

[Sum with varargs](https://rosettacode.org/wiki/Variadic_function#Forth)
`: sum ( x_1 ... x_n n -- sum ) 1 ?do + loop ;`

**Comment by nomennescio** [comment]
In the scope of this simple framework, and given the nature of Forth's stacks, user code is able to manipulate the stacks to the point were tests can break. However, it is not possible to accidently pass a test.
